<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>MSPChallenge_Simulation_Example</RootNamespace>
    <ApplicationIcon>ApplicationIcon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="ApplicationIcon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Clipper2" Version="2.0.0" />
    <PackageReference Include="DotNetEnv" Version="3.1.1" />
    <PackageReference Include="DotSpatial.Projections" Version="4.0.656" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.8" />
    <PackageReference Include="ModelContextProtocol" Version="0.5.0-preview.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="Stateless" Version="5.16.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
  </ItemGroup>

  <ItemGroup>
    <None Include=".http\1.Watchdog-UpdateState-Setup.http" />
    <None Include=".http\2.Watchdog-UpdateState-Simulate.http" />
    <None Include=".http\3.Watchdog-SetMonth.http" />
    <None Include=".http\4.Watchdog-UpdateState-End.http" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="README-source\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="dockerfile">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="DownloadModelData.bat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="RunDockerContainer.bat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="SimSettings.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
